import Header from "@/components/header";
import Footer from "@/components/footer";

import "./globals.css";

export const metadata = {
  title: "App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className="grid grid-rows-[auto_1fr_auto] min-h-screen">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}



